### ISSUE TITLE
when i use react-hot-loader

### ISSUE THREAD

**Issue by zhongjie-chen** [emiloberg/webpack-tutorial#1]
```javascript
  webpack.config.js
  loaders: [
        'react-hot-loader',
        'babel-loader',
        'eslint-loader'
      ],
  .babelrc
  "presets": [
    ["es2015", { "modules": false }],
    "stage-0",
    "react"
  ],
```
crash log
![image](https://cloud.githubusercontent.com/assets/14540231/22862689/858291b4-f16e-11e6-8267-a507b82e0051.png)

**Comment by emiloberg** [comment]
It looks like you've an `import` or `export` inside your `index.js`, somewhere where it's not allowed to be. Strictly speaking, all your imports should be at the top of your file.
